### ISSUE TITLE
creare server in bianco

### ISSUE THREAD

**Issue by capponiFelice92** [capponiFelice92/catalogo-prodotti#2]

**Comment by capponiFelice92** [comment]
Creare scheletro del progetto:
-creare server con spring initializr
-gestire application.properties
-creare tutti i packages con i file necessari vuoti
-inserire annotazioni MAIN CLASS
-definire main class in properties/run ecc...

**Comment by nicoloabatecola** [comment]
Completato

**Comment by capponiFelice92** [comment]
perfetto
